# Generated by Django 3.2 on 2021-05-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S',
        ),
    ]
