# Generated by Django 3.2 on 2021-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_desciption_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='curier',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма доставки'),
        ),
        migrations.AlterField(
            model_name='storage_worker',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма доставки'),
        ),
    ]
