# Generated by Django 3.2 on 2021-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210614_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
