# Generated by Django 3.2 on 2022-01-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='curier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='storage_worker',
        ),
        migrations.RemoveField(
            model_name='storage_worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storageroom',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='storageroom',
            name='storage_conditions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='product',
            name='export_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_conditions',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.DeleteModel(
            name='Curier',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='Storage_Conditions',
        ),
        migrations.DeleteModel(
            name='Storage_Worker',
        ),
        migrations.DeleteModel(
            name='StorageRoom',
        ),
    ]
